features = [
  'Type',
 'Episodes',
 'Release_year',
 'Release_season',
 'Studio',
 'warnings_count',
 'rel_anim_count',
 'rel_mang_count',
 'voice_act_count',
 'rel_media_count',
 'staff_count',
 'tags_count',
 'Action',
 ' Adventure',
 ' Fantasy',
 ' Shounen',
 ' Demons',
 ' Historical',
 ' Martial Arts',
 ' Orphans',
 ' Siblings',
 ' Swordplay',
 ' Based on a Manga',
 ' Explicit Violence',
 'Drama',
 ' Romance',
 ' Shoujo',
 ' Contemporary Fantasy',
 '',
 ' Mature Themes',
 ' Physical Abuse',
 ' Suicide',
 ' Violence',
 'Fantasy',
 ' Ancient China',
 ' Chinese Animation',
 ' Based on a Web Novel',
 ' Drama',
 ' Mystery',
 ' Military',
 ' Horror',
 ' Dark Fantasy',
 ' Post-apocalyptic',
 ' Monsters',
 ' School Life',
 ' Supernatural',
 ' War',
 'Shounen',
 ' Sports',
 ' School Club',
 ' Tournaments',
 ' Original Work',
 ' Comedy',
 ' Superpowers',
 ' Melancholy',
 ' Based on a Light Novel',
 'BL',
 ' Shounen-ai',
 ' Non-Human Protagonists',
 ' Royalty',
 ' Isekai',
 ' Magic',
 ' Person in a Strange World',
 ' Political',
 ' Reincarnation',
 ' RPG',
 ' Music',
 ' noitaminA',
 'Mecha',
 ' Sci Fi',
 ' Overpowered Main Characters',
 ' Psychological',
 ' Real Robot',
 ' Aliens',
 ' Feudal Japan',
 ' Gag',
 ' Parody',
 ' Samurai',
 ' Time Travel',
 ' Urban Fantasy',
 ' Psychic Powers',
 'Comedy',
 ' Love Triangle',
 ' Thriller',
 'Adventure',
 ' Family Friendly',
 ' Japanese Mythology',
 ' Youkai',
 ' Coming of Age',
 ' Crude',
 ' Slapstick',
 ' Adult Couples',
 ' Based on a Visual Novel',
 ' America',
 ' Criminals',
 ' Gangs',
 ' Sexual Abuse',
 ' CG Animation',
 'Sci Fi',
 ' Seinen',
 ' Cyborgs',
 ' Superheroes',
 ' Lifestyle Change',
 ' Based on a Novel',
 ' Cats',
 ' Countryside',
 ' Episodic',
 ' Iyashikei',
 ' Europe',
 ' Medieval',
 ' Revenge',
 ' Slice of Life',
 ' Animal Characteristics',
 ' Nudity',
 ' Racing',
 ' Hand to Hand Combat',
 ' Monster-of-the-week',
 ' Proxy Battles',
 ' Recap',
 ' Mature Romance',
 ' Sexual Content',
 ' Forest',
 'Chibi',
 ' Korean Animation',
 ' Romantic Comedy',
 ' Outer Space',
 ' Ecchi',
 ' Vampires',
 ' Based on a Video Game',
 ' Androids',
 ' Robots',
 ' 19th Century',
 ' Josei',
 ' Chibi',
 ' Short Episodes',
 ' Work Life',
 ' Animal Protagonists',
 ' Anthropomorphic',
 'Mystery',
 ' Detectives',
 ' Based on an Eroge',
 ' Otaku Culture',
 ' Virtual Reality',
 ' Guns',
 ' Explicit Sex',
 ' Food and Beverage',
 ' Island',
 ' Baseball',
 ' Mecha',
 ' Super Robot',
 ' High Stakes Games',
 ' Harem',
 'Sports',
 ' Ninja',
 ' Birds',
 ' Police',
 ' Insects',
 ' Based on a 4-Koma Manga',
 ' Cars',
 ' Elemental Powers',
 'Seinen',
 ' Idols',
 ' Showbiz',
 ' Magical Girl',
 ' Henshin Heroes',
 'Horror',
 ' Thieves',
 ' Ocean',
 ' Shorts',
 ' Coworkers',
 'Romance',
 'Slice of Life',
 ' Panty Shots',
 ' Promotional',
 ' Abstract',
 ' Based on a Mobile Game',
 ' Crossover',
 'Ecchi',
 ' Pets',
 ' No Dialogue',
 ' Based on a Fairy Tale',
 ' Sanrio Characters',
 'Idols',
 ' Soccer',
 ' Dogs',
 ' Bears',
 'Commercials',
 ' Flash Animation',
 ' Educational',
 ' Based on a Card Game',
 ' Pigs',
 'Vocaloid',
 ' Stop Motion Animation',
 'Abstract',
 ' Vocaloid',
 ' Rabbits',
 'Magical Girl',
 ' Card Battles',
 ' Black and White',
 'Family Friendly',
 'Animal Protagonists',
 'Promotional',
 'Educational',
 'Chinese Animation',
 ' Food Protagonists',
 ' Commercials',
 ' Based on a Picture Book',
 'No Dialogue',
 'Shorts',
 'Black and White',
 ' Minna no Uta',
 'Minna no Uta',
 'cw_Explicit Violence',
 'cw_Emotional Abuse',
 'cw_ Mature Themes',
 'cw_ Physical Abuse',
 'cw_ Suicide',
 'cw_ Violence',
 'cw_ Domestic Abuse',
 'cw_Animal Abuse',
 'cw_Cannibalism',
 'cw_ Explicit Violence',
 'cw_Mature Themes',
 'cw_Violence',
 'cw_Bullying',
 'cw_ Emotional Abuse',
 'cw_ Self-Harm',
 'cw_Physical Abuse',
 'cw_Drug Use',
 'cw_ Prostitution',
 'cw_ Sexual Abuse',
 'cw_Nudity',
 'cw_ Sexual Content',
 'cw_ Nudity',
 'cw_Explicit Sex',
 'cw_ Bullying',
 'cw_Sexual Content',
 'cw_ Explicit Sex',
 'cw_Domestic Abuse',
 'cw_ Drug Use',
 'cw_Incest',
 'cw_Suicide',
 'cw_ Incest'
]